### ISSUE TITLE
Can't deploy on vercel

### ISSUE THREAD

**Issue by hosykynam0619ch2008-umego** [Strange1108/Zoom-Clone#1]
Hi I'm trying to deploy one on my vercel, but doesn't seems to work, how did you get it to work on vercel?
<img width="1470" alt="Ảnh màn hình 2024-09-30 lúc 8 54 38 CH" src="https://github.com/user-attachments/assets/b1b6dfba-0ea9-42fa-a51d-77ed0d24d3b9">

**Comment by Strange1108** [comment]
Hi,

Here’s a quick guide on how I deployed my project on Vercel:

Push your project to a public GitHub repository.
1. Head over to [Vercel](https://vercel.com/).
2. Click on "Add New Project."
3. Import the Git repository (find your project from GitHub).
4. Copy the environment variables from your .env.local file (Ctrl+C).
5. Go to the "Environment Variables" section in Vercel and add all the variables (Ctrl+V).
6. Deploy the project.
7. Once deployed, continue to the Dashboard.
8. Copy the domain name of your Vercel project.
9. Navigate to Settings -> Environment Variables, find NEXT_PUBLIC_URL, and update it to the new domain name you just copied. Don’t forget to save.
10. Go back to the "Deployments" tab, click on the three dots next to the latest deployment, and select Redeploy.
11. Wait for a minute, and your project should be live!

Hope this helps! Let me know if you run into any issues.
![Environment Variables](https://github.com/user-attachments/assets/057105a0-9dda-40bb-b04c-43e050d2b258)

**Comment by hosykynam0619ch2008-umego** [comment]
Thanks! It works.
<img width="1470" alt="Ảnh màn hình 2024-10-01 lúc 2 56 39 CH" src="https://github.com/user-attachments/assets/442f3269-c984-4b11-bc94-fbac3f524f81">
